config/routes.rb
PillphoneWeb::Application.routes.draw do

  
  resources :users do
    collection do
      post 'login'
    end
  end

  
  get "users_medication/mymed"
  get "drugs/index"
  post "users_medication/add_to_my_med"
  get "users/back"
  post "drugs/add_to_my_med"
  post "users_medication/remove_my_med"
  delete "users_medication/remove"
  post "users/logout"
  root to: 'users#index'
  
 

  

end

app/models/drug.rb
class Drug < ActiveRecord::Base
	has_many :users, :through => :user_medications
	has_many :user_medications
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :drugs, :through => :user_medications
	has_many :user_medications
	   validates :name,    :presence => true
	   validates :address, :presence => true
	   validates :email,   :presence => true, :uniqueness => true, on: :login
	   validates :password,:presence => true,                      on: :login
	   validates :phone,   :presence => true
	   validates :age,     :presence => true
   # validates :type,    :presence => true
   validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/user_medication.rb
class UserMedication < ActiveRecord::Base
	belongs_to :user
	belongs_to :drug
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authorize
  protect_from_forgery with: :exception
  protected
		def authorize
			unless User.find_by_id(session[:user_id])
				#redirect_to login_users_path, :notice => "please log in"
			end
		end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
	#before_action :set_user_drug, only: [:index]
	def index
		@drugs = Drug.all
	end
		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#skip_before_filter :authorize, :only => [:login, :create]
	def login
		if @user=User.find_by_email_and_password(params[:email],params[:password])
			session[:user_id]=@user.id
			redirect_to @user
		else
			puts "Check your details again!"
			redirect_to users_path
		end
	end

	def new
		@user= User.new
	end

	 def create
   # Not the final implementation!
		@user = User.new(name:params[:name], address:params[:address], age:params[:age], email:params[:email], phone:params[:phone], password:params[:password])
        @user.save
       respond_to do |format|
	        if @user.save
	         
	         	 format.html { redirect_to users_url }
		         format.xml { render :xml => @user,:status => :created, :location => @user }
		         format.html { redirect_to @user, notice: 'User was successfully created.' }
		         format.json { render action: 'show', status: :created, location: @user }
	      	else
	            format.html { render action: 'new' }
	        	format.json { render json: @user.errors, status: :unprocessable_entity }
	      	end
    	end
    end

  	def show
  		@current_user = User.find(session[:user_id])
  	end

  	def logout
  		session[:user_id]=nil
  		redirect_to users_path
  	end

	private	
			def set_user
				#@user= User.find(params[:id])
			end

			def user_params
				#params.require(:user).permit(:name, :address, :password, :email, :phone, :age, :type)
			end
end

app/controllers/users_medication_controller.rb
class UsersMedicationController < ApplicationController 
	#before_action :set_user_med, only: [:mymed, :add_to_my_med, :remove_my_med]
	def mymed
	@u=User.find(session[:user_id]).user_medications
	
	end

	def add_to_my_med
		@user= User.find(session[:user_id])
		@user.user_medications.create(:dosage=>params[:dosage],:drug_id=>params[:drug_id])
		redirect_to users_medication_mymed_path
	end

	def remove_my_med
		@u=UserMedication.find(params[:user_medication])
		@u.destroy
		redirect_to users_medication_mymed_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_medication_helper.rb
module UserMedicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drugs/index.html.erb
<h3><%="These are all the Medications:" %></h3>
<h3><p align="right"><%= link_to 'Back', users_back_url %> </p></h3>
<div id="drug_list" >

<table>
  <tr>
    <th>Drug_Id</th>
    <th>Drug_Name_Long</th>
    <th>Drug_Name_Short</th>
    <th>Generic_Name</th>
    <th>Add_To_My_Med</th>
    <th>Dosage</th>
  </tr>
 
<% @drugs.each do |drug| %>
  <tr>
    <td><%= drug.id%></td>
    <td><%= drug.drug_name_long %></td>
    <td><%= drug.drug_name_short %></td>
    <td><%=drug.generic_name %></td>
    <td><%= button_to "Add To Med" ,{:controller => 'users_medication', :action=> "add_to_my_med" ,:drug_id=> drug.id},:method => 'post' %></td>
    <td><%= text_field_tag :dosage , params[:dosage] %>
  </tr>
<% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>PillphoneWeb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<body style="background-color:GREY;">
</body>
</html>

app/views/users/_form.html.erb
<%= form_tag(controller: "users", action: "create", method: "post") do %>
 
 <% if @user.errors.any? %>
       <div id="error_explanation">
       <h2><%= pluralize(@user.errors.count, "error") %> 
          prohibited this user from being saved:</h2>
       <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
      </div>
  <% end %>
  
<fieldset><center>
  <h4> Welcome to Pillphone app ! Enter your details to sign up! </h4>
  <div><b><%= label_tag(:name, "Name:   ") %>
  <%= text_field_tag(:name) %>
 <br></div><br>
  <div><%= label_tag(:address, "Address:") %>
  <%= text_field_tag(:address) %></div>
 <br>
 <div><%= label_tag(:email,    "Email:  ") %>
  <%= text_field_tag(:email) %></div>
 <br>
 <div><%= label_tag(:password, "Password:") %>
  <%= text_field_tag(:password) %></div>
  <br>
  <div><%= label_tag(:age,     "Age:     ") %>
  <%= text_field_tag(:age) %></div>
 <br>
  <div><%= label_tag(:phone,   "Phone:   ") %>
  <%= text_field_tag(:phone) %></div>
 <br>
 <div>
  <%= submit_tag("submit") %></b>
</div>
  <% end %>
  </center></fieldset>

app/views/users/index.html.erb
<%= form_tag(controller: "users", action: "login", method: "post") do %>
<center><h4><u> Welcome to Pillphone Web app! </u></h4></center>

<fieldset>
	<center>
	<h3> Login </h3>
<%= label_tag(:email,    "Email:  ") %>
  <%= text_field_tag(:email) %>
 <br>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>
  <br>
  <%= submit_tag("Login") %></b>
</center>
  </fieldset>


  <fieldset>
  	<br>
	<center><%= link_to 'Signup', new_user_path %></br></center>
</fieldset>	
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h2>Welcome <%= @current_user.name %></h2>
It's <%= Time.now %>
<h3> What would you like to do? </h3>
<fieldset><center>
<%= link_to 'My Medications', users_medication_mymed_path %></br>
<%= link_to 'View all the Drugs', drugs_index_path %></br>
<%#= link_to 'Messages', messages_path %>
<br>
<%= button_to "Logout" , {:controller =>"users" ,:action=> "logout" },:method => 'post' %>
</center></fieldset>

app/views/users_medication/_form.html.erb
welcome

app/views/users_medication/add_to_my_med.html.erb
<h2><%= 'You have added the following drug to your medication list #{@drugs_drug.id}'%></h2>

app/views/users_medication/mymed.html.erb
<h1>These are your Medications</h1>


<br>
<fieldset><center>
	<table border="1">
		<tr>
     <th>Medication_Id</th>
    <th>Medication</th>
    <th>User_ID</th>

    <th>Dosage</th>
    <th></th>
  </tr>
<% @u.each do |u| %>
<tr>
<td><%= u.id %></td>
<td><%= u.drug_id %></td>
<td><%= u.user_id %></td>
<td><%= u.dosage %></td>
<td><%= button_to "Delete Med" ,{:controller =>"users_medication" ,:action=> "remove_my_med" , :user_medication=> u.id },:method => 'post' %></td></tr>
<% end %>
</table>
<%= link_to 'Back', users_back_url %>
<%= link_to 'Logout', users_path %><br>

</center></fieldset>